### PR TITLE
remove Sindri tasks and configuration

### PR DESCRIPTION
**Pull request by francois-vincent**

### CODE REVIEW

**Comment by buildbotctp** [comment]
Build finished. No test results found.

**Comment by antoine-de** [comment]
Jenkins, test this please

**Comment by antoine-de** [comment]
test this please

**Comment by buildbotctp** [comment]
Build finished. No test results found.

**Comment by antoine-de** [comment]
Jenkins, test this please

**Comment by antoine-de** [comment]
test this please

**Comment by antoine-de** [comment]
Jenkins, test this please

**Comment by antoine-de** [comment]
Jenkins, test this please

**Comment by antoine-de** [comment]
Jenkins, test this please

**Comment by francois-vincent** [comment]
Jenkins, test this please

**Pull request merged**
