### PR TITLE
add task to update setuptools on all platform's hosts

### PR DESCRIPTION
**Pull request by francois-vincent**

### CODE REVIEW

**Comment by kinnou02** [comment]
test doesn't pass.

And I don't see the point,since this task is never called.

**Comment by francois-vincent** [comment]
tests result seem random, but it is irrelevant
I shall fix this when integration test framework is merged

**Comment by francois-vincent** [comment]
in jenkins, the fabric invocation will be changed to:
PYTHONPATH=/etc/navitia_deployment_conf/ python -u -m fabric use:artemis fix_setuptools upgrade_version

**Comment by kinnou02** [comment]
It's look like band-aid on a wooden leg...
It would be easier to not do an upgrade by default more over because we can also upgrade system packages (since we don't use virtualenv), one day we will break something.

**Comment by francois-vincent** [comment]
It's not band-aid, it's a fix
we currently do this *by hand* on all machines before any deployment, at least this fix will save some time
moreover, for jenkins driven deployments, I have no other working alternative

**Comment by antoine-de** [comment]
isn't it possible just to remove the `-U` from the fabric's `pip install`
uses ?

**Comment by francois-vincent** [comment]
do it another way in another PR

**Pull request closed without merging**
